[project]
name = "be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite",
    "earthengine-api",
    "fastapi[standard]>=0.128.0",
    "openai-agents[sqlalchemy]",
    "pebble",
    "planetary-computer",
    "pyproj",
    "pystac-client",
    "shapely",
    "odc-stac",
    "xarray",
    "uvicorn>=0.40.0",
    "aiomysql>=0.3.2",
    "asyncpg>=0.31.0",
]
